### ISSUE TITLE
Count deployments by released tag event on Github

### ISSUE THREAD

**Issue by omer2500** [middlewarehq/middleware#622]
Hi!

Our ci/cd process includes production workflows that are triggered when a release gets released
```
name: deploy_production
on:
  release:
    types:
      - released
```
Do you know if there is support for that? I mean I was able to choose my workflow name when I added the repository but didn't see any data no matter what range I set

Thanks.
